<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>moe</string>
	</array>
	<key>name</key>
	<string>Moe</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#translation_unit</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block-comment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.source.moe</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comment</string>
				</dict>
			</array>
		</dict>
		<key>cast</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.moe</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.moe</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(cast)\s*\((?:\*|\^)*(.+?)\)</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#line-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-comment</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false|null)\b</string>
					<key>name</key>
					<string>constant.language.source.moe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)0[xX][[:xdigit:]]+</string>
					<key>name</key>
					<string>constant.numeric.hexadecimal.source.moe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)\d+(?:\.\d+)?</string>
					<key>name</key>
					<string>constant.numeric.decimal.source.moe</string>
				</dict>
			</array>
		</dict>
		<key>enum</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.enum.source.moe</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.enum.source.moe</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+)\s*(enum)\b</string>
		</dict>
		<key>function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function_declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_use</string>
				</dict>
			</array>
		</dict>
		<key>function_declaration</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.function.source.moe entity.name.function.source.moe</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.source.moe</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-zA-Z_]\w*)\b\s*(proc)\s*[\(]</string>
		</dict>
		<key>function_use</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.source.moe</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?!(while|for|if|else|return|continue|then|acast|defer|cast|sizeof|alignof|using|inline|no_inline)\s+)([a-zA-Z_]\w*)\s*[\(]</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#\w*</string>
					<key>name</key>
					<string>keyword.other.directive.source.moe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:if|else|for|for_each|while|continue|break|switch|case|fallthrough|default|return)\b</string>
					<key>name</key>
					<string>keyword.control.source.moe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:acast|sizeof|alignof|typeinfo|typedef|new|delete)\b</string>
					<key>name</key>
					<string>keyword.operator.source.moe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:defer|using)\b</string>
					<key>name</key>
					<string>keyword.other.source.moe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>---</string>
					<key>name</key>
					<string>keyword.other.source.moe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(it|it_index|context)\b</string>
					<key>name</key>
					<string>keyword.other.source.moe</string>
				</dict>
			</array>
		</dict>
		<key>line-comment</key>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.source.moe</string>
		</dict>
		<key>storage</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:SOA|AOS|inline|no_inline)\b</string>
					<key>name</key>
					<string>storage.modifier.source.moe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:void|string|bool|float|f32|f64|int|u8|u16|u32|u64|s8|s16|s32|s64|Any)\b</string>
					<key>name</key>
					<string>storage.type.source.moe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([A-Z][a-z0-9]+)([_][A-Z][a-z0-9]*)*\b</string>
					<key>name</key>
					<string>storage.type.source.moe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[A-Z_](?![a-z])[A-Z_0-9]+\b</string>
					<key>name</key>
					<string>storage.constant.moe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>".*?"</string>
					<key>name</key>
					<string>string.quoted.double.source.moe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$\b\w+\b</string>
					<key>name</key>
					<string>storage.type.source.moe</string>
				</dict>
			</array>
		</dict>
		<key>struct</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.struct.source.moe</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.struct.source.moe</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+)\s*(struct)\b</string>
		</dict>
		<key>translation_unit</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cast</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#enum</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#storage</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.moe</string>
	<key>uuid</key>
	<string>3971aca2-2c80-4745-9e8b-8b1d95a5af33</string>
</dict>
</plist>
